## 라이브러리 불러오기

In [1]:
import numpy as np

In [2]:
# numpy 라이브러리가 없다면? (numpy 는 동일한 타입만 넣을 수 있다. )
!pip install numpy

### 1차원 배열(array) 만들기

numpy쓰는 이유 
 list는 계산이 안되고 list에 더하기를 하면 list요소만 추가됨 여러형태혼합 가능 - 바보
 arr - 인덱스번호대로 연산이됨. 동시에 여러형태안됨.

In [4]:
list1 = [1,2,3,4,5]

In [5]:
type(list1)

list

In [8]:
arr1 = np.array(list1) # numpy에 있는 array라는 자료형
arr1

array([1, 2, 3, 4, 5])

In [9]:
type(arr1)

numpy.ndarray

### 2차원 배열 생성하기

In [13]:
list2 = [[1,2,3],[4,5,6]] #2차원 list를 생성
arr2 = np.array(list2) #2차원 numpy배열을 생성하는 코드
arr2 # 2차원 array

array([[1, 2, 3],
       [4, 5, 6]])

### 데이터 확인하기
- 배열의 크기 (shape) -> (행, 열)
- 배열의 개수 (size) -> 요소의 개수
- 배열의 차원(ndim) 

In [14]:
# 배열의 크기 : 배열.shape
arr2.shape #(행,열)

(2, 3)

In [15]:
# 배열의 개수 확인 : 배열.size
arr2.size # 총 요소의 개수 

6

In [19]:
# 배열의 차원 확인 : 배열.ndim
print(arr1.ndim)
print(arr2.ndim)

1
2


In [20]:
list3 = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr3 = np.array(list3)
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
print(f'배열의 크기 : {arr3.shape}')
print('배열의 요소 개수 : {}'.format(arr3.size))
print('배열의 차원 : %d'%(arr3.ndim))

배열의 크기 : (2, 2, 2)
배열의 요소 개수 : 8
배열의 차원 : 3


#### 배열의 연산
- 요소별 연산이 가능하다! 

In [24]:
list1=[1,2,3]
list2=[4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

In [29]:
print(arr1)
arr1 + arr1

[1 2 3 4 5]


array([ 2,  4,  6,  8, 10])

In [30]:
#정수형과 실수형도 연산이 가능하다 
arr4 = np.array([1.2,2.2,3.3,4.4,5.5])

In [31]:
arr1+arr4

array([ 2.2,  4.2,  6.3,  8.4, 10.5])

### 인덱싱, 슬라이싱(범위)
- 인덱싱 : 가리킨다 라는 의미 - > 한개의 데이터를 찾아온다.
- 슬라이싱 : 잘라온다 라는 의미 -> 한개 이상의 데이터를 찾아온다
- 하는 이유 : 내가 원하는 데이터에 접근하기 위해서, 손쉽게 데이터를 찾아가기 위해서 

In [33]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# 숫자 2 가져오기
arr[0][1]

2

In [36]:
# 2차원 배열 인덱싱하는 또 다른 방법
arr[0,1] #[행,열]

2

In [37]:
#슬라이싱 > 2~5까지 슬라이싱
arr_1 = np.array([0,1,2,3,4,5,6,7,8,9])
arr_1[2:6] # 슬라이싱 - > 변수명 [시작 : 끝+1]

array([2, 3, 4, 5])

In [38]:
# 3~ 끝 슬라이싱
arr_1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# [:끝값+1] : 처음부터 내가 가져오고 싶은 값까지
#[시작:]: 내가 가져오고 싶은 값부터 끝까지
#[:] : 전체 데이터를 출력하고 싶을때

### BMI 지수 구하기

In [64]:
# 데이터 로드하기!
data = np.loadtxt('height_weight(p).txt',delimiter=',')
data

array([[175.2   , 180.3   , 175.    , 169.2   , 185.2   , 188.    ,
        177.6   , 178.2   , 177.    , 179.    ],
       [144.5824, 193.952 , 174.5568, 152.7372, 121.22  , 156.9248,
        160.892 , 151.8556, 163.096 , 180.728 ]])

In [60]:
# 몸무게 데이터 인덱싱 해오기

# 몸무게 데이터(p) - > (kg) *0.454

# 키데이터 (cm) 

# 키데이터(cm)->(m) /100

#BMI지수 구하기 

In [65]:
weight = data[1]*0.454

In [66]:
height = data[0]/100
height

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [68]:
bmi = weight/height**2
bmi

array([21.3846959 , 27.08685992, 25.877155  , 24.22144007, 16.04531206,
       20.15727116, 23.1581776 , 21.71057199, 23.63483801, 25.60797478])

### 여러가지 방법으로 넘파이 배열 생성하기
- 배열을 특정한 값으로 초기화해서 생성하기


In [72]:
# 배열 안의 모든 데이터 0으로 초기화해서 생성하는 방법
# np.zeros((행,열))(배열의 크기 -> 튜플형태로 작성할것
arr_zero = np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# 소괄호 안쪽에 숫자 하나만 적어주면 1차원 배열이 생성된다.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
# 배열안의 모든 데이터를 1로 초기화 해서 생성
# np.ones(배열의 크기(행,열)) 
np.ones((3,4)) #3행 4열

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
# 내가 원하는 특정값으로 초기화해서 배열 생성
#np.full((행,열),내가 원하는 값)
np.full((2,3),(7))

array([[7, 7, 7],
       [7, 7, 7]])

- 1부터 50까지 숫자데이터를 가지고 있는 1차원 배열 생성

In [92]:
list_f = []
for i in range(1,51,1):
    list_f.append(i) 

In [94]:
list_f
np.array(list_f)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [95]:
#순차적으로 증가하거나 감소하는 배열을 생성
#arange(시작,끝+1,증감값)
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [96]:
# 1부터 51까지 4씩 증가하는 배열
np.arange(1,52,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

- 랜덤값으로 초기화 하면서 생성


In [108]:
#np.random.randint(시작값, 끝값+1, size=(배열의 크기(행,열)))
np.random.randint(1,51,size = (2,3))# 2행 3열

array([[36, 23, 16],
       [15, 14,  6]])

In [123]:
# 스스로 1차원 배열 1~50까지 출력
np.arange(1,51)
# 2차원 배열로 (5행10열) .reshape(행,열)
arr_2 = np.arange(1,51).reshape(5,10)
arr_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [111]:
#arr_2에서 15,16,17 가져오기

In [118]:
arr_2[1,4:7] #[행,열]

array([15, 16, 17])

In [ ]:
# 전체 행의 0열만 가져오기 

In [119]:
arr_2[1][0]

11

In [135]:
arr_2[0:5,0] # 전체를 가져오는 기호 :
arr_2[:,0]

array([ 1, 11, 21, 31, 41])

In [137]:
#3행의 전체 열을 출력
arr_2[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [163]:
#22,23 출력 
arr_2[[2,3],[1,2]]
#[[행],[열]]
#[[행1,행2,행3],[열1,열2,열3]]

array([22, 33])

### 불리언 색인(인덱싱)
- 조건에 해당하는(True) 값들만 출력할때 사용
- 내가 찾고자하는 원본데이터 [조건식]- 조건식안에는 불리언 형태여야함(true/false)

In [164]:
# 임의의 점수데이터
score = np.array([65,90,70,80,55])
score

array([65, 90, 70, 80, 55])

In [165]:
#현재는 논리연산의 결과 
score>=70

array([False,  True,  True,  True, False])

In [168]:
# 논리연산이 참인 값들만 가져온다 
score[score>=70]

array([90, 70, 80])

In [169]:
# 이름 데이터
name = np.array(['주희','진영','진이','현성','준기'])
name

array(['주희', '진영', '진이', '현성', '준기'], dtype='<U2')

In [170]:
name[score>=70]

array(['진영', '진이', '현성'], dtype='<U2')

### 범용함수
- 넘파이에서 제공해주는 함수

In [180]:
# sum()
arr= np.random.randint(0,10,size = (2,5))
arr
print(np.sum(arr))

31


In [182]:
# mean() ---> 평균값을 구해주는 함수 
np.mean(arr)

3.1

In [183]:
# sqrt() ---> 제곱근을 구해주는 함수
arr1 = np.array([1,4,9,16,25])
np.sqrt(arr1)

array([1., 2., 3., 4., 5.])

In [185]:
# abs --> 절대값을 구해주는 함수
arr2 = np.array([-5,-8,5,1,2,-6])
np.abs(arr2)

array([5, 8, 5, 1, 2, 6])